version: 3

vars:
  wd: /workspace

tasks:
  default:
    cmds:
      - task: lint
      - task: test

  lint:
    summary: Lints Protobuf and Go.
    cmds:
      - docker run --rm -v "$(pwd):{{.wd}}" -w {{.wd}} bufbuild/buf:1.31 lint
      - golangci-lint run ./...

  test:
    summary: Tests the lib end to end.
    cmds:
      - go install .
      - go test -v ./...

  generate:
    summary: Generates Go from Protobuf.
    cmds:
      - docker run --rm -v "$(pwd):/{{.wd}}" -w {{.wd}} bufbuild/buf:1.31 generate
