version: 3

vars:
  WD: /workspace
  BUF_VERSION: 1.45
  BUF_COMMAND: docker run --rm -v "$(pwd):{{.WD}}" -w {{.WD}} bufbuild/buf:{{.BUF_VERSION}}

tasks:
  default:
    cmds:
      - task: lint
      - task: test

  lint:
    summary: Lints Protobuf and Go.
    cmds:
      - '{{.BUF_COMMAND}} lint'
      - golangci-lint run ./...

  test:
    summary: Tests the lib end to end.
    cmds:
      - go install ./cmd/protoc-gen-openapi
      - go test -v ./cmd/...

  generate:
    summary: Generates Go from Protobuf.
    cmds:
      - docker run --rm -v "$(pwd):{{.WD}}" -w {{.WD}} bufbuild/buf:{{.BUF_VERSION}} generate
