name: Lint

on:
  workflow_call:
    inputs:
      lint_proto:
        type: boolean
        default: true
      lint_go:
        type: boolean
        default: true

jobs:
  lint_proto:
    name: Lint Proto
    runs-on: ubuntu-latest
    if: ${{ inputs.lint_proto }}
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: api
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: api
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=${{github.ref_name}},ref=HEAD~1'

  lint_go:
    name: Lint Go
    runs-on: ubuntu-latest
    if: ${{ inputs.lint_go }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          check-latest: true
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
